### ISSUE TITLE
coordinate

### ISSUE THREAD

**Issue by chengzhangsuper** [TomStog/Infrared-BP#3]
Can you share the volunteer RGB screenshot dataset?

**Comment by chengzhangsuper** [comment]
Can you share the volunteer RGB screenshot dataset?

**Comment by TomStog** [comment]
Unfortunately I can't due to privacy protocols applied.

**Comment by TomStog** [comment]
Basically I just recorded a few seconds with our camera in RGB mode before switching to Infrared

**Comment by chengzhangsuper** [comment]
Can you upload some pictures used in the code? I want to run it, thank you        img = cv2.imread('18.png')  image = cv2.imread('08.png')
  with open('18.txt', 'w') as file:

**Comment by TomStog** [comment]
Again, I'm very sorry but I can't, volunteers' data cannot be shared.

**Comment by TomStog** [comment]
We can work this through, but you need to help me a bit. I need data, you need data. If you are willing to share any future data, then I'll be able to help you back.

**Comment by chengzhangsuper** [comment]
I’m having a holiday these days so I forgot to reply. If you help me, I’m willing to share my future data.

**Comment by TomStog** [comment]
I uploaded a sample image for you to study the experimental setup. The face has been swaped with an artificially generated one. Further instructions can be found in the 3rd section of our paper, called "EXPERIMENTS". I also twiked a bit the "face_tracking_dnn_photo.py", "hand_detect4bloodpressure_photo.py" files. Nothing too exciting, just some minor additions in order to save the coordinates of the face and hand in MATLAB's coordinate system format. If your future video data setup can match our setup, that would be a tremendous help.

**Comment by TomStog** [comment]
And please let me know when you're planning to start builiding your dataset. Thank you.

**Comment by chengzhangsuper** [comment]
My teacher asked me to prepare the data set after understanding the code and running it successfully.

**Comment by TomStog** [comment]
I'm willing to offer an intensive course (Skype/Zoom/Microsoft Teams) covering the methodology, the literature I utilized, and a thorough explanation of the code to assist you in successfully reproducing my results, if you're able to secure a commitment from at least 30 volunteers and maintain the video format closely resembling the uploaded sample image and provide the data within a month.

**Comment by TomStog** [comment]
Check this:
https://www.mdpi.com/2673-7426/4/1/25
